-- MySQL Script generated by MySQL Workbench
-- Mon Feb 25 17:17:16 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `id` INT NOT NULL,
  `wechatid` VARCHAR(45) NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `type` ENUM('Visitor', 'Member', 'Agent', 'Admin') NULL DEFAULT 'Vistor',
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `mydb`.`estate`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`estate` (
  `id` INT NOT NULL,
  `tag` VARCHAR(45) NULL,
  `price` INT NOT NULL,
  `description` TEXT(500) NULL,
  `adress_num` INT NULL,
  `adress_St` CHAR(20) NULL,
  `adress_suburb` CHAR(20) NULL,
  `adress_city` CHAR(20) NULL,
  `adress_state` CHAR(20) NULL,
  `adress_country` CHAR(20) NULL DEFAULT 'Australia',
  `type` ENUM('Apartment', 'House', 'Town House') NULL DEFAULT ',
  `room` TINYINT(0) NULL,
  `kitchen` TINYINT(0) NULL,
  `toilet` TINYINT(0) NULL,
  `livingroom` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`picture`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`picture` (
  `id` INT NOT NULL,
  `estate_id` INT NOT NULL,
  `picture` MEDIUMBLOB NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_picture_estate_idx` (`estate_id` ASC) VISIBLE,
  CONSTRAINT `fk_picture_estate`
    FOREIGN KEY (`estate_id`)
    REFERENCES `mydb`.`estate` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`admin` (
  `admin_id` INT NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NULL,
  `create_time` TIMESTAMP NULL,
  PRIMARY KEY (`admin_id`),
  CONSTRAINT `fk_admin_user1`
    FOREIGN KEY (`admin_id`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`agent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`agent` (
  `agent_id` INT NOT NULL,
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(32) NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX `fk_agent_user1_idx` (`agent_id` ASC) VISIBLE,
  PRIMARY KEY (`agent_id`),
  CONSTRAINT `fk_agent_user1`
    FOREIGN KEY (`agent_id`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`agent_publish_estate`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`agent_publish_estate` (
  `agent_agent_id` INT NOT NULL,
  `estate_id` INT NOT NULL,
  `estate_agent_agent_id` INT NOT NULL,
  `commission_persentatge` FLOAT NULL,
  `commission_fixed` INT NULL,
  `commission_description` TEXT(500) NULL,
  `published` TINYINT NULL,
  PRIMARY KEY (`agent_agent_id`, `estate_id`, `estate_agent_agent_id`),
  INDEX `fk_agent_has_estate_estate1_idx` (`estate_id` ASC, `estate_agent_agent_id` ASC) VISIBLE,
  INDEX `fk_agent_has_estate_agent1_idx` (`agent_agent_id` ASC) VISIBLE,
  CONSTRAINT `fk_agent_has_estate_agent1`
    FOREIGN KEY (`agent_agent_id`)
    REFERENCES `mydb`.`agent` (`agent_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_agent_has_estate_estate1`
    FOREIGN KEY (`estate_id`)
    REFERENCES `mydb`.`estate` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`member`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`member` (
  `user_id` INT NOT NULL,
  `member_timestamp` TIMESTAMP NOT NULL,
  `account_valid` ENUM('YES', 'NO') NOT NULL DEFAULT 'NO',
  PRIMARY KEY (`user_id`),
  INDEX `fk_member_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_member_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`purchases`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`purchases` (
  `id` INT NOT NULL,
  `member_user_id` INT NOT NULL,
  `start_time` TIMESTAMP NOT NULL,
  `end_time` TIMESTAMP NOT NULL,
  `purchase_amount` FLOAT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_purchases_member1_idx` (`member_user_id` ASC) VISIBLE,
  CONSTRAINT `fk_purchases_member1`
    FOREIGN KEY (`member_user_id`)
    REFERENCES `mydb`.`member` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`member_subscribe_estate`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`member_subscribe_estate` (
  `member_user_id` INT NOT NULL,
  `estate_id` INT NOT NULL,
  `estate_agent_agent_id` INT NOT NULL,
  `tag` VARCHAR(45) NULL,
  `adress_suburb` CHAR(20) NULL,
  `price_max` INT NULL,
  `price_min` INT NULL,
  `type` ENUM('Apartment', 'House', 'Town House') NULL,
  `room` TINYINT(0) NULL,
  `kitchen` TINYINT(0) NULL,
  `garage` TINYINT(0) NULL,
  `living_room` TINYINT(0) NULL,
  `balcony` TINYINT(0) NULL,
  `garden` TINYINT(0) NULL,
  PRIMARY KEY (`member_user_id`, `estate_id`, `estate_agent_agent_id`),
  INDEX `fk_member_has_estate_estate1_idx` (`estate_id` ASC, `estate_agent_agent_id` ASC) VISIBLE,
  INDEX `fk_member_has_estate_member1_idx` (`member_user_id` ASC) VISIBLE,
  CONSTRAINT `fk_member_has_estate_member1`
    FOREIGN KEY (`member_user_id`)
    REFERENCES `mydb`.`member` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_member_has_estate_estate1`
    FOREIGN KEY (`estate_id`)
    REFERENCES `mydb`.`estate` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user_like_estate`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user_like_estate` (
  `user_id` INT NOT NULL,
  `estate_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `estate_id`),
  INDEX `fk_user_has_estate_estate1_idx` (`estate_id` ASC) VISIBLE,
  INDEX `fk_user_has_estate_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_has_estate_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_estate_estate1`
    FOREIGN KEY (`estate_id`)
    REFERENCES `mydb`.`estate` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
